In [36]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# Introduction to Tensors

## Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [37]:
# scalar
scalar  = torch.tensor(7)
scalar

tensor(7)

In [38]:
# get tensor back as an integer
scalar.item()

7

In [39]:
vector = torch.tensor([7, 7])

In [40]:
vector.ndim

1

In [41]:
vector.shape

torch.Size([2])

In [42]:
# MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
MATRIX.ndim

2

In [44]:
MATRIX.shape

torch.Size([3, 3])

In [45]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [46]:
TENSOR.ndim

3

In [47]:
TENSOR.shape

torch.Size([1, 3, 3])

In [48]:
TENSOR[0][1][1]

tensor(5)

### Random Twnsors

Why random tensors?

Random tensors are important because if the way many neural networks learn, they start with tensors full of random numbers and then adjust those numbers to better represent data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numberss`

PyTorch rand = https://pytorch.org/docs/stable/generated/torch.rand.html

In [59]:
# Create a random tensor of size 3x4

random_tensor = torch.rand(3,4)
random_tensor.shape, random_tensor.ndim, random_tensor

(torch.Size([3, 4]),
 2,
 tensor([[0.7177, 0.6843, 0.1569, 0.7716],
         [0.1577, 0.3059, 0.9245, 0.8014],
         [0.3140, 0.1272, 0.9840, 0.3285]]))

In [60]:
# Create a random tensor similar to an imagae tensor

random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]),
 3,
 tensor([[[0.5139, 0.3443, 0.9580,  ..., 0.4820, 0.3609, 0.9204],
          [0.8032, 0.3680, 0.5076,  ..., 0.3078, 0.6331, 0.5801],
          [0.9765, 0.3191, 0.7616,  ..., 0.1887, 0.5261, 0.3056],
          ...,
          [0.6501, 0.0375, 0.8181,  ..., 0.9700, 0.2674, 0.4248],
          [0.5963, 0.2219, 0.3932,  ..., 0.8407, 0.6878, 0.3575],
          [0.1140, 0.4962, 0.7918,  ..., 0.0345, 0.1553, 0.2793]],
 
         [[0.9777, 0.4212, 0.3739,  ..., 0.1434, 0.5994, 0.0452],
          [0.6878, 0.2028, 0.3406,  ..., 0.0426, 0.8080, 0.3406],
          [0.9309, 0.5694, 0.4064,  ..., 0.9493, 0.2526, 0.8135],
          ...,
          [0.8969, 0.0098, 0.2718,  ..., 0.7469, 0.9929, 0.4720],
          [0.2089, 0.3703, 0.6539,  ..., 0.0201, 0.2296, 0.1624],
          [0.9085, 0.2680, 0.9264,  ..., 0.2515, 0.6110, 0.1908]],
 
         [[0.3385, 0.1894, 0.5047,  ..., 0.7752, 0.6328, 0.5930],
          [0.8325, 0.5161, 0.2797,  ..., 0.6660, 0.5129, 0.8737],
        

In [62]:
# Zeros and ones

zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros,ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [74]:
# Creating a tensor in range, torch.range() is deprecated, use torch.arange()

ranged_tensor = torch.arange(1,11)
ranged_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
zeroes = torch.zeros_like(input=ranged_tensor)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Note:** Tensor datatypes are one of the 3 big issues I will run into while using PyTorch and deep learning

1. Tensors not the right datatype
1. Tensors not on the right device
1. Tensors not in the right shape

In [78]:
float_32_tensor = torch.tensor([3.0, 60., 9.0], dtype=None, device="cpu", requires_grad=False)
float_32_tensor.dtype

torch.float32